#!/bin/sh

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
insmod -f mapmanager.ko

major=`cat /proc/devices | awk "\\$2==\"mapmanager\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's simple that has several devices in it.

rm -f /dev/mapmanager
mknod /dev/mapmanager c $major 0
chmod 666  /dev/mapmanager

###################################
# Add all simulated modules to be loaded here
# Use same format as for mapmanager
# TODO load simulator list from file 

# example simulator
insmod -f examplesimulator.ko
rm -f /dev/examplesimulator
mknod /dev/examplesimulator c $major 0
chmod 666  /dev/examplesimulator
###################################

###################################
# Add all device drivers to be loaded here
# Use same format as for mapmanager
# TODO load driver list from file 

# example driver
insmod -f exampledriver.ko
major=`cat /proc/devices | awk "\\$2==\"exampledriver\" {print \\$1}"`
rm -f /dev/exampledriver
mknod /dev/exampledriver c $major 0
chmod 666  /dev/exampledriver


