#!/bin/sh

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
insmod -f mapmanager.ko

major=`cat /proc/devices | awk "\\$2==\"mapmanager\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's simple that has several devices in it.

rm -f /dev/mapmanager
mknod /dev/mapmanager c $major 0
chmod 666  /dev/mapmanager
